#!python3

# creating this to test some more things, feel free to delete
# when you are done testing.

import numpy as np
import pandas
import matplotlib as mpl

def circle_area(r):
  return r^2 * np.pi
